### ISSUE TITLE
When running the code "Run the Tests" some errors occurred

### ISSUE THREAD

**Issue by zhang-mu-zhi** [smlbansal/Visual-Navigation-Release#5]
I have followed the instruction and established the environment successfully.
When I run the command“PYOPENGL_PLATFORM=egl PYTHONPATH='.' python executables/run_all_tests.py”.
I got an Error：

`  File "/home/zhangmuzhi/Visual-Navigation-Release-master/mp_env/sbpd.py", line 52, in load_building_meshes
    mesh_file_name = glob.glob1(dir_name, '*.obj')[1]
IndexError: list index out of range
Execution time for test test_obstacle_objective.py is 2 seconds.

Test failed: test_obstacle_objective.py`

What should I do next?

**Comment by vatsuak** [comment]
Hi, I think the function is looking for an .obj file and cannot find it.  You can check if the obj files are present by running,
`find . -type f -name "*.obj"`
 in the LB_WayPtNav_Data_Public/ directory, it should give you some outputs like,
`./stanford_building_parser_dataset/mesh/area1/5acd38aa86ea42028a265d20947754f5.obj
./stanford_building_parser_dataset/mesh/area3/41a8012778ff4fc1800a7794bd15d81e.obj
`  

Also, make sure you followed the steps in [here](https://github.com/smlbansal/Visual-Navigation-Release/tree/master/sbpd). 

Additionally check if the path to the data is set correctly by running,
`python -c "import base_data_directory as bd;print(bd.base_data_dir())"`
in the params folder.

Hope that helps!

**Comment by zhang-mu-zhi** [comment]
I followed the instructions in "Configure LB-WayptNav to look for your data installation." and changed "`PATH/TO`" in the code "`return 'PATH/TO/LB_WayPtNav_Data'`" to the path where my "`.obj`" file is located, Then it ran successfully.

**Comment by zhang-mu-zhi** [comment]
I followed the instructions in "**Configure LB-WayptNav to look for your data installation.**" and changed "`PATH/TO`" in the code "`return 'PATH/TO/LB_WayPtNav_Data'`" `to the path where my` "`.obj`" file is located, Then it ran successfully.

**Comment by vatsuak** [comment]
Closing because solved!
